import {
  Anchor,
  Atom,
  Bell,
  Bomb,
  Bot,
  Camera,
  Cherry,
  Cloud,
  Compass,
  Crown,
  Diamond,
  Feather,
  Flame,
  Flower2,
  Gem,
  Heart,
  Hexagon,
  Leaf,
  Moon,
  Mountain,
  Rocket,
  Sparkles,
  Star,
  Sun,
  Swords,
  Trees,
  Trophy,
  Waves,
  Wheat,
  Zap,
  Orbit,
  Fish
} from "lucide-react";

export const iconPool = [
  { id: "star", component: Star },
  { id: "rocket", component: Rocket },
  { id: "heart", component: Heart },
  { id: "sun", component: Sun },
  { id: "moon", component: Moon },
  { id: "flame", component: Flame },
  { id: "leaf", component: Leaf },
  { id: "feather", component: Feather },
  { id: "gem", component: Gem },
  { id: "atom", component: Atom },
  { id: "crown", component: Crown },
  { id: "cloud", component: Cloud },
  { id: "waves", component: Waves },
  { id: "mountain", component: Mountain },
  { id: "trees", component: Trees },
  { id: "flower", component: Flower2 },
  { id: "zap", component: Zap },
  { id: "sparkles", component: Sparkles },
  { id: "cherry", component: Cherry },
  { id: "camera", component: Camera },
  { id: "anchor", component: Anchor },
  { id: "compass", component: Compass },
  { id: "diamond", component: Diamond },
  { id: "trophy", component: Trophy },
  { id: "hexagon", component: Hexagon },
  { id: "bell", component: Bell },
  { id: "bomb", component: Bomb },
  { id: "swords", component: Swords },
  { id: "wheat", component: Wheat },
  { id: "bot", component: Bot },
  { id: "orbit", component: Orbit },
  { id: "fish", component: Fish }
] as const;

export const tintPalette = [
  "#00e7ff",
  "#7cfb7f",
  "#ffd56f",
  "#ff8fab",
  "#72a5ff",
  "#c495ff",
  "#6fffe9",
  "#f7a072"
];
